### ISSUE TITLE
Missing notes can cause hitting any notes to become impossible.

### ISSUE THREAD

**Issue by Arcadris** [The-SGPT/FunkinChaos#8]
Sometimes when missing a note you will be unable to hit any notes and attempting to will do nothing not even cause a miss if a note isnt there.

**Comment by Arcadris** [comment]
Seems to happen more often when missing tails of long notes

**Comment by haya3218** [comment]
Tried this at B-Sides-Milf and it does. Hmmmm.
This only happened after I made a few things for missing notes when you dont hit it.
Gonna try fixing

**Comment by haya3218** [comment]
I think I may have fixed it, but it allows people to do spam.
Eh, whatever.

**Comment by haya3218** [comment]
closing dis
thanks for info!
